
/** Required package class namespace */
package userinterfaces;

/** Required import */
import controllers.LoginController;

/**
 * LoginUI.java - the user interface view that appears for the user to interact
 * and login to the application with
 * 
 * @author Wen Pei (Michael) Yan
 * @since Feb, 2023
 */
public class LoginUI extends javax.swing.JFrame {
    
    // Connection to an encapsulated controller for this user interface
    private LoginController controller;

    /**
     * Creates new form LoginUI and sets the properties of the frame
     */
    public LoginUI() {
        initComponents();
        controller = new LoginController(this, jTextName, jTextPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextPassword = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        jTextName.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        getContentPane().add(jTextName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jLabel8.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 170, 30));

        jTextPassword.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        getContentPane().add(jTextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        jButtonLogin.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        controller.login(jTextName.getText(), jTextPassword.getText());
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.closing();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPassword;
    // End of variables declaration//GEN-END:variables
}
