
/** Required package class namespace */
package userinterfaces;

/** Required imports */
import controllers.OrderController;
import data.OrderData;

/**
 * OrderUI.java - the user interface view that appears and acts like an ordering
 * menu for the user with all the necessary interactions to create an order and
 * to generate a receipt
 *
 * @author Wen Pei (Michael) Yan
 * @since Feb, 2023
 */
public class OrderUI extends javax.swing.JFrame {

    // Connection to an encapsulated controller for this user interface
    private OrderController controller;

    /**
     * Creates new form OrderUI and connects to the order controller
     */
    public OrderUI() {
        initComponents();
        controller = new OrderController(
                this,
                jTableOrder,
                jTextSubTotal,
                jTextTax,
                jTextTotal,
                jComboBoxPayment,
                jTextAmount,
                jTextChange,
                jLabelItems,
                jButtonItem1,
                jButtonItem2,
                jButtonItem3,
                jButtonItem4,
                jButtonItem5,
                jButtonItem6,
                jTextFieldCustomerName,
                jTextFieldNumber,
                jTextFieldAddress,
                jComboBoxOrderType);
        // Sets item buttons to start with appetizers
        controller.setItems(
                jButtonAppetizers.getText(),
                OrderData.APPETIZER_NAMES,
                OrderData.APPETIZER_PRICES);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jComboBoxOrderType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jTextSubTotal = new javax.swing.JTextField();
        jTextTax = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextAmount = new javax.swing.JTextField();
        jTextChange = new javax.swing.JTextField();
        jComboBoxPayment = new javax.swing.JComboBox<>();
        jButtonPay = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonReset = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButtonMisc = new javax.swing.JButton();
        jButtonGreens = new javax.swing.JButton();
        jButtonCombos = new javax.swing.JButton();
        jButtonSpecials = new javax.swing.JButton();
        jButtonSeafood = new javax.swing.JButton();
        jButtonBeef = new javax.swing.JButton();
        jButtonPork = new javax.swing.JButton();
        jButtonChicken = new javax.swing.JButton();
        jButtonNoodles = new javax.swing.JButton();
        jButtonRice = new javax.swing.JButton();
        jButtonSoups = new javax.swing.JButton();
        jButtonAppetizers = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonItem1 = new javax.swing.JButton();
        jButtonItem3 = new javax.swing.JButton();
        jButtonItem5 = new javax.swing.JButton();
        jButtonItem6 = new javax.swing.JButton();
        jButtonItem4 = new javax.swing.JButton();
        jButtonItem2 = new javax.swing.JButton();
        jLabelItems = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCustomerName.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jPanel1.add(jTextFieldCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        jLabel7.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel7.setText("Customer Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jLabel8.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel8.setText("Number:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 30));

        jTextFieldNumber.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jPanel1.add(jTextFieldNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 30));

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel9.setText("Order Type:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 190, 30));

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, 30));

        jTextFieldAddress.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jPanel1.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, 30));

        jComboBoxOrderType.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jComboBoxOrderType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Take-out", "Dine-in", "Pick-up" }));
        jComboBoxOrderType.setSelectedIndex(-1);
        jPanel1.add(jComboBoxOrderType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 150));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel1.setText("TOTAL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 50));

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel2.setText("Sub Total");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel3.setText("Tax");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 50));

        jTextTotal.setEditable(false);
        jTextTotal.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jTextTotal.setText("0.00");
        jPanel2.add(jTextTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jTextSubTotal.setEditable(false);
        jTextSubTotal.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jTextSubTotal.setText("0.00");
        jPanel2.add(jTextSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 210, -1));

        jTextTax.setEditable(false);
        jTextTax.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jTextTax.setText("0.00");
        jPanel2.add(jTextTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 400, 160));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel4.setText("Payment");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        jLabel5.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel5.setText("Amount");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 50));

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel6.setText("Change");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 50));

        jTextAmount.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jPanel3.add(jTextAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 210, -1));

        jTextChange.setEditable(false);
        jTextChange.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jTextChange.setText("0.00");
        jPanel3.add(jTextChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 210, -1));

        jComboBoxPayment.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jComboBoxPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit", "Credit" }));
        jComboBoxPayment.setSelectedIndex(-1);
        jPanel3.add(jComboBoxPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 210, 40));

        jButtonPay.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonPay.setText("Pay");
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 160, 140));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 570, 160));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReset.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 270, 80));

        jButtonRemove.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 80));

        jButtonMenu.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonMenu.setText("Menu");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 270, 80));

        jButtonLogout.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 270, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 570, 190));

        jTableOrder.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Amount", "Cost"
            }
        ));
        jTableOrder.setRowHeight(23);
        jScrollPane1.setViewportView(jTableOrder);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 400, 440));

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMisc.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonMisc.setText("Misc");
        jButtonMisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMiscActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonMisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 130, 120));

        jButtonGreens.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonGreens.setText("Greens");
        jButtonGreens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGreensActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonGreens, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 120));

        jButtonCombos.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonCombos.setText("Combos");
        jButtonCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCombosActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonCombos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 130, 120));

        jButtonSpecials.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonSpecials.setText("Specials");
        jButtonSpecials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpecialsActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSpecials, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 130, 120));

        jButtonSeafood.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonSeafood.setText("Seafood");
        jButtonSeafood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeafoodActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSeafood, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 130, 120));

        jButtonBeef.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonBeef.setText("Beef");
        jButtonBeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeefActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonBeef, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 130, 120));

        jButtonPork.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonPork.setText("Pork");
        jButtonPork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPorkActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonPork, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, 120));

        jButtonChicken.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonChicken.setText("Chicken");
        jButtonChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChickenActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonChicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, 120));

        jButtonNoodles.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonNoodles.setText("Noodles");
        jButtonNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoodlesActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonNoodles, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 130, 120));

        jButtonRice.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonRice.setText("Rice");
        jButtonRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRiceActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonRice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 120));

        jButtonSoups.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonSoups.setText("Soups");
        jButtonSoups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSoupsActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSoups, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 130, 120));

        jButtonAppetizers.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonAppetizers.setText("Appetizers");
        jButtonAppetizers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAppetizersActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonAppetizers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 120));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 570, 400));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonItem1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItem1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 200));

        jButtonItem3.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItem3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, 200));

        jButtonItem5.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItem5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 200, 200));

        jButtonItem6.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItem6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonItem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 200, 200));

        jButtonItem4.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItem4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 200, 200));

        jButtonItem2.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItem2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, 200));

        jLabelItems.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabelItems.setText("Categories:");
        jPanel5.add(jLabelItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 120));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 430, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAppetizersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAppetizersActionPerformed
        controller.setItems(
                jButtonAppetizers.getText(),
                OrderData.APPETIZER_NAMES,
                OrderData.APPETIZER_PRICES);
    }//GEN-LAST:event_jButtonAppetizersActionPerformed

    private void jButtonItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItem1ActionPerformed
        controller.addItem(jButtonItem1.getText(), 0);
    }//GEN-LAST:event_jButtonItem1ActionPerformed

    private void jButtonItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItem3ActionPerformed
        controller.addItem(jButtonItem3.getText(), 2);
    }//GEN-LAST:event_jButtonItem3ActionPerformed

    private void jButtonItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItem5ActionPerformed
        controller.addItem(jButtonItem5.getText(), 4);
    }//GEN-LAST:event_jButtonItem5ActionPerformed

    private void jButtonItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItem6ActionPerformed
        controller.addItem(jButtonItem6.getText(), 5);
    }//GEN-LAST:event_jButtonItem6ActionPerformed

    private void jButtonItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItem4ActionPerformed
        controller.addItem(jButtonItem4.getText(), 3);
    }//GEN-LAST:event_jButtonItem4ActionPerformed

    private void jButtonItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItem2ActionPerformed
        controller.addItem(jButtonItem2.getText(), 1);
    }//GEN-LAST:event_jButtonItem2ActionPerformed

    private void jButtonSoupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoupsActionPerformed
        controller.setItems(
                jButtonSoups.getText(),
                OrderData.SOUP_NAMES,
                OrderData.SOUP_PRICES);
    }//GEN-LAST:event_jButtonSoupsActionPerformed

    private void jButtonRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRiceActionPerformed
        controller.setItems(
                jButtonRice.getText(),
                OrderData.RICE_NAMES,
                OrderData.RICE_PRICES);
    }//GEN-LAST:event_jButtonRiceActionPerformed

    private void jButtonNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoodlesActionPerformed
        controller.setItems(
                jButtonNoodles.getText(),
                OrderData.NOODLE_NAMES,
                OrderData.NOODLE_PRICES);
    }//GEN-LAST:event_jButtonNoodlesActionPerformed

    private void jButtonChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChickenActionPerformed
        controller.setItems(
                jButtonChicken.getText(),
                OrderData.CHICKEN_NAMES,
                OrderData.CHICKEN_PRICES);
    }//GEN-LAST:event_jButtonChickenActionPerformed

    private void jButtonPorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorkActionPerformed
        controller.setItems(
                jButtonPork.getText(),
                OrderData.PORK_NAMES,
                OrderData.PORK_PRICES);
    }//GEN-LAST:event_jButtonPorkActionPerformed

    private void jButtonBeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeefActionPerformed
        controller.setItems(
                jButtonBeef.getText(),
                OrderData.BEEF_NAMES,
                OrderData.BEEF_PRICES);
    }//GEN-LAST:event_jButtonBeefActionPerformed

    private void jButtonSeafoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeafoodActionPerformed
        controller.setItems(
                jButtonSeafood.getText(),
                OrderData.SEAFOOD_NAMES,
                OrderData.SEAFOOD_PRICES);
    }//GEN-LAST:event_jButtonSeafoodActionPerformed

    private void jButtonGreensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGreensActionPerformed
        controller.setItems(
                jButtonGreens.getText(),
                OrderData.VEGETABLE_NAMES,
                OrderData.VEGETABLE_PRICES);
    }//GEN-LAST:event_jButtonGreensActionPerformed

    private void jButtonCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCombosActionPerformed
        controller.setItems(
                jButtonCombos.getText(),
                OrderData.COMBO_NAMES,
                OrderData.COMBO_PRICES);
    }//GEN-LAST:event_jButtonCombosActionPerformed

    private void jButtonSpecialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpecialsActionPerformed
        controller.setItems(
                jButtonSpecials.getText(),
                OrderData.SPECIALS_NAMES,
                OrderData.SPECIALS_PRICES);
    }//GEN-LAST:event_jButtonSpecialsActionPerformed

    private void jButtonMiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMiscActionPerformed
        controller.setItems(
                jButtonMisc.getText(),
                OrderData.MISC_NAMES,
                OrderData.MISC_PRICES);
    }//GEN-LAST:event_jButtonMiscActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        controller.logout();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        controller.reset();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        controller.menu();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        controller.removeItem();
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
        controller.pay();
    }//GEN-LAST:event_jButtonPayActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.closing();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAppetizers;
    private javax.swing.JButton jButtonBeef;
    private javax.swing.JButton jButtonChicken;
    private javax.swing.JButton jButtonCombos;
    private javax.swing.JButton jButtonGreens;
    private javax.swing.JButton jButtonItem1;
    private javax.swing.JButton jButtonItem2;
    private javax.swing.JButton jButtonItem3;
    private javax.swing.JButton jButtonItem4;
    private javax.swing.JButton jButtonItem5;
    private javax.swing.JButton jButtonItem6;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonMisc;
    private javax.swing.JButton jButtonNoodles;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JButton jButtonPork;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonRice;
    private javax.swing.JButton jButtonSeafood;
    private javax.swing.JButton jButtonSoups;
    private javax.swing.JButton jButtonSpecials;
    private javax.swing.JComboBox<String> jComboBoxOrderType;
    private javax.swing.JComboBox<String> jComboBoxPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelItems;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTextField jTextAmount;
    private javax.swing.JTextField jTextChange;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCustomerName;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTax;
    private javax.swing.JTextField jTextTotal;
    // End of variables declaration//GEN-END:variables
}
