
/** Required package class namespace */
package userinterfaces;

/** Required imports */
import controllers.ViewReceiptController;
import data.DataStructures;

/**
 * ReceiptUI.java - the user interface view that appears and displays a list
 * of all the receipts saved in as a file, allowing for deletion and viewing
 * 
 * @author mikex
 */
public class ReceiptUI extends javax.swing.JFrame {
    
    // Connection to an encapsulated controller for this user interface
    private ViewReceiptController controller;

    /**
     * Creates new form ReceiptsUI and sets the properties of the frame
     */
    public ReceiptUI() {
        initComponents();
        setFrame();
        controller = new ViewReceiptController(receiptList);
        DataStructures.receipts.displayAll(receiptList);
    }
    
    /**
     * Sets the visual properties of the JFrame
     */
    private void setFrame() {
        // Sets the title of the window
        setTitle("Restaurant");
        // Sets the size of the window
        setSize(500, 800);
        // Sets the location to show up in the middle (null) 
        this.setLocationRelativeTo(null);
        // Sets the frame to be visible
        setVisible(true);
        // Sets the frame resizable property to false
        setResizable(false);
        // Sets to dispose on close
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiptList = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxSort = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextSearch = new javax.swing.JTextField();
        jButtonMenu = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonOpen1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(receiptList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 350, 440));

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel9.setText("Search:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        jComboBoxSort.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        getContentPane().add(jComboBoxSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 260, 30));

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel10.setText("Sort:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jTextSearch.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        getContentPane().add(jTextSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 260, 30));

        jButtonMenu.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonMenu.setText("Menu");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 350, 40));

        jButtonDelete.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 170, 40));

        jButtonOpen1.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jButtonOpen1.setText("Open");
        jButtonOpen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpen1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOpen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        controller.closing(this);
        controller.menu();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        DataStructures.receipts.deleteSelected(receiptList.getSelectedIndex(),
                receiptList);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.closing(this);
    }//GEN-LAST:event_formWindowClosing

    private void jButtonOpen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpen1ActionPerformed
        controller.displaySelectedReceipt();
    }//GEN-LAST:event_jButtonOpen1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonOpen1;
    private javax.swing.JComboBox<String> jComboBoxSort;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextSearch;
    private java.awt.List receiptList;
    // End of variables declaration//GEN-END:variables
}
